apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: product-catalog-chatbot # Executable ID (max length 64 lowercase-hyphen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `first-pipeline-1234`
  annotations:
    scenarios.ai.sap.com/name: "Product Catalog Chatbot: Scenario"
    scenarios.ai.sap.com/description: "Chatbot for product catalog"
    executables.ai.sap.com/name: "Product Catalog Chatbot: Executable"
    executables.ai.sap.com/description: "Chatbot for product catalog"
  labels:
    scenarios.ai.sap.com/id: "product-catalog-chatbot" # The scenario ID to which the serving template belongs
    ai.sap.com/version: "0.0.1"
spec:
  imagePullSecrets:
    - name: credstutorialrepo-kho # your docker registry secret
     container:
      image: kevindlw/product-catalog-chatbot:0.1 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/main.py"
     
