apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: genai-training-product-catalog # Executable ID (max length 64 lowercase-hyphen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `first-pipeline-1234`
  annotations:
    scenarios.ai.sap.com/name: "genAI training scenario: Product catalog chatbot"
    scenarios.ai.sap.com/description: "A chatbot trained on a product catalog"
    executables.ai.sap.com/name: "genAI training executable: Product catalog chatbot"
    executables.ai.sap.com/description: "A chatbot trained on a product catalog"
  labels:
    scenarios.ai.sap.com/id: "genai-training-product-catalog-chatbot" # The scenario ID to which the serving template belongs
    ai.sap.com/version: "0.0.1"
spec:
  imagePullSecrets:
    - name: credstutorialrepo-kho # your docker registry secret
  entrypoint: genai-training
  templates:
  - name: genai-training
    metadata:
        labels:
          ai.sap.com/resourcePlan: Basic-8x
    container:
      image: docker.io/kevindlw/genai-training:0.1 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/train-predict.py"
     environment:
          - AICORE_AUTH_URL=${AICORE_AUTH_URL}
          - AICORE_CLIENT_ID=${AICORE_CLIENT_ID}
          - AICORE_CLIENT_SECRET=${AICORE_CLIENT_SECRET}
          - AICORE_BASE_URL=${AICORE_BASE_URL}
          - HANA_DB_ADDRESS=${HANA_DB_ADDRESS}
          - HANA_DB_PORT=${HANA_DB_PORT}
          - HANA_DB_USER=${HANA_DB_USER}
          - HANA_DB_PASSWORD=${HANA_DB_PASSWORD}
   
